ec-config:
  conf:
    mod: api
    app: ec
    apt: "17990"
    dbg: true
    tls: false
    oa2: http://localhost:17991
    cid: <your-account-id-aka-dev-id>
  #available in oauth2, api, x:gateway, and watcher for TLS purpose. ceredential can be used in both cred, and authGroup segments  
  cred:
    privateKey: <private key base64 string>
    publicCrt: <public cert base64 string>
