ec-config:
  conf:
    mod: server
    zon: e2sd834-28be-4851-9d6a-b7033d568270
    grp: 012ss19-int
    sst: https://esdfsfc834-28be-4851-9d6a-b7033d568270.run.aws-usw02-dev.ice.predix.io
    hst: ws://localhost:18990/agent
    dbg: true
    cid: cid
    csc: csc
    oa2: https://asrfrsf53-6d3e-4c14-9d7a-85891e1ff2db.predix-uaa.run.aws-usw02-dev.ice.predix.io/oauth/token
    dur: 300
    aid: <aid>
    rpt: "18998"
    rht: localhost
    plg: true
    cps: 5
