ec-config:
  conf:
    mod: x:client
    hst: ws://localhost:47990/agent
    tid: 0dd8ab7b-9b78-4283-ad21-586636fhello
    cid: 0dd8ab7b-9b78-4283-ad21-586636fhello
    oa2: http://yasuda-pc:17991
    dbg: true
    grp: x-pilot
    lpt: "27990"
    cps: 5
    #file upload/download. temp solutioning
    #fup: agent_busybox:agent_busybox_1
    #fdw: agent_busybox:agent_busybox_2
  watcher:
    env: LOCAL
    license: SERVER_X5 #cert
    role: DEVELOPER #cert
    devId: 0dd8ab7b-9b78-4283-ad21-586636f7bad1
    scope: app.auth #cert
    certsDir: "/etc/ssl/certs"
    mode: x:client #cert. available option: gateway,server,client,gw:server,gw:client
    os: darwin
    arch: amd64
    instance: 3
    duration: 1
    cpuPeriod: 100000 #microsec. e.g. 50000/100000 = .5 cpu
    cpuQuota: 50000
    in-memory: 134217728 #in bytes. ~128mb
    swap-memory: 67108864
    oauth2: http://localhost:17993
    Http_Port: ":17991"
    Tcp_Port: ":17990"
    Custom_Port: ":17992" #the watcher container will bind the port to the host for custom usage
    contRev: v1beta.fukuoka.1725
    watrRev: v1.1beta.fukuoka.2727
    contArtURL: https://raw.githubusercontent.com/Enterprise-connect/sdk/{{contRev}}/dist/ecagent_arm_sys.tar.gz
    watrArtURL: https://raw.githubusercontent.com/Enterprise-connect/sdk/{{watrRev}}/dist/agent/ecagent_arm_sys.tar.gz
  plugins:
  - name: vln
    url: https://raw.githubusercontent.com/Enterprise-connect/sdk/{{revision}}/plugins/{{name}}/vln_darwin_sys
  - name: tls
    url: https://raw.githubusercontent.com/Enterprise-connect/sdk/{{revision}}/plugins/{{name}}/tls_darwin_sys
